name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  release:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  run-ts: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
       - name: Run TS action
         uses: ./
         with: 
          milliseconds: 1000
