name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  release:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
       - name: Publish action 
         uses: actions-on-packages/package-action@0.2.0
