name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
#   release:
  push:
    branches:
      - main
      - 'releases/*'
      
  workflow_dispatch:

jobs:
  run-ts: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v3
         
       - name: Run TS action
         uses: ./
         with: 
          milliseconds: 1000
       
       - name: Testing reusable workflows
         uses: actions-on-packages/hello-world-go-action/.github/workflows/use_ts_action.yml@main
